### ISSUE TITLE
SE Toolbox Location Problem

### ISSUE THREAD

**Issue by TomSeptim1996** [midspace/SEToolbox#170]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [ ] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 1.189.33 
**SE Version:** 1.191.020

### SEToolbox crashed
What were you doing with SEToolbox when it happened?
started the program and the locate app pop up also my SE is in the normal location put it still does not work I have also tried every thing

**Comment by realzap** [comment]
Hi, im facing the same. It occurs on on Win10. The Tollbox ask directly where the the SE.exe is located. Thats in my case "D:\Steam\steamapps\common\SpaceEngineers\Bin64\SpaceEngineers.exe" and i can see and select it by using the folder butten - back in the Screen the path will be also displayed correct. 

Error Mesage is "Invalid location specified".

Only the cancel Button is active.

SEToolbox Version: 1.189.33
SE Version: 1.191.020

I testet the msi packet, the "de" msi packet and the zip file. It occurs on all of them.

Not sure if this is a local Problem on my PC or we have a problem with the last Update.

**Comment by midspace** [comment]
**Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.**

**Comment by midspace** [comment]
Apologies. It looks like the release (done a couple of hours ago) was still marked draft for some reason.
It's fixed now.

**Comment by realzap** [comment]
Confirmed - its works !!!

Midspace you are great - Thank You !!!

**Comment by Derpingtonthethird** [comment]
Same issue here...
Also I have installed the latest release and it still doesn't work

**Comment by sh4yd9w** [comment]
Hey, I'm having this issue with the most updated version, can someone help?
